services:
    adminLotes_service:
        class:     AppBundle\Service\AdminLotesService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    eliminarAcciones_service:
        class:     AppBundle\Service\EliminarAccionesService
        arguments:
            { container: @service_container, entityManager: "@doctrine.orm.entity_manager" }

    app.admin.producto:
        class: AppBundle\Admin\ProductoAdmin
        arguments: [~, AppBundle\Entity\Producto, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Producto }

    app.admin.lote:
        class: AppBundle\Admin\LoteAdmin
        arguments: [~, AppBundle\Entity\Lote, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Lote }

    app.admin.proveedor:
        class: AppBundle\Admin\ProveedorAdmin
        arguments: [~, AppBundle\Entity\Proveedor, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Proveedor }
        public: true

    app.admin.compra:
        class: AppBundle\Admin\CompraAdmin
        arguments: [~, AppBundle\Entity\Compra, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Compra }
        public: true

    app.admin.cliente:
        class: AppBundle\Admin\ClienteAdmin
        arguments: [~, AppBundle\Entity\Cliente, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cliente }
        public: true

    app.admin.formula_enzimatica:
        class: AppBundle\Admin\FormulaEnzimaticaAdmin
        arguments: [~, AppBundle\Entity\FormulaEnzimatica, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FormulaEnzimatica }
        public: true

    app.admin.remito:
        class: AppBundle\Admin\RemitoAdmin
        arguments: [~, AppBundle\Entity\Remito, AppBundle:RemitoCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Remito }
        public: true

    app.admin.fabricacion:
        class: AppBundle\Admin\FabricacionAdmin
        arguments: [~, AppBundle\Entity\Fabricacion, , AppBundle:FabricacionCRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Fabricacion }
        public: true
