services:
    app.admin.producto:
        class: AppBundle\Admin\ProductoAdmin
        arguments: [~, AppBundle\Entity\Producto, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Producto }

    app.admin.lote:
        class: AppBundle\Admin\LoteAdmin
        arguments: [~, AppBundle\Entity\Lote, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Lote }

    app.admin.proveedor:
        class: AppBundle\Admin\ProveedorAdmin
        arguments: [~, AppBundle\Entity\Proveedor, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Proveedor }
        public: true

    app.admin.compra:
        class: AppBundle\Admin\CompraAdmin
        arguments: [~, AppBundle\Entity\Compra, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Compra }
        public: true

    app.admin.cliente:
        class: AppBundle\Admin\ClienteAdmin
        arguments: [~, AppBundle\Entity\Cliente, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Cliente }
        public: true

    app.admin.tipo_fabricacion:
        class: AppBundle\Admin\TipoFabricacionAdmin
        arguments: [~, AppBundle\Entity\TipoFabricacion, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: TipoFabricacion }
        public: true
