<?php

namespace AppBundle\Repository;

/**
 * FabricacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricacionRepository extends \Doctrine\ORM\EntityRepository
{
}
