<?php

namespace AppBundle\Repository;

/**
 * FabricacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FabricacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUltimoMes()
	{
		$previousMonth = new \DateTime();
	    $previousMonth->sub (new \DateInterval ('P1M'));

	    $qb = $this->createQueryBuilder("r");
	    $qb
	        ->andWhere('r.fechaModificacion > :previousMonth')
	        ->setParameter('previousMonth', $previousMonth )
	        ->orderBy('r.fechaModificacion', 'DESC');
	    ;
	    $result = $qb->getQuery()->getResult();

	    return $result;
	}
}
