<?php

namespace AppBundle\Repository;

/**
 * FormulaEnzimaticaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormulaEnzimaticaRepository extends \Doctrine\ORM\EntityRepository
{
}
