<?php

namespace AppBundle\Repository;

/**
 * ItemRemitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRemitoRepository extends \Doctrine\ORM\EntityRepository
{
}
