<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Lote;

/**
 * LoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class LoteRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * fetches Products that are more expansive than the given price
	 * 
	 * @param int $price
	 * @return array
	 */
	public function loteCantidadMayorACero($producto, $cantidadEstado)
	{

	  $em = $this->getEntityManager();
	  $qb = $em->createQueryBuilder();

	  $q  = $qb->select(array('l'))
	           ->from(Lote::class, 'l')
	           ->where(
	             $qb->expr()->gt('l.'.$cantidadEstado, 0),
	             $qb->expr()->eq('l.producto', $producto->getId())
	           )
	           ->orderBy('l.fecha', 'ASC')
	           ->getQuery();

	  return $q->getResult();
	}

	public function sumDe($producto, $cantidadEstado) {
		$sql = $this->createQueryBuilder('l')
	        ->select('SUM(l.'.$cantidadEstado.') AS total')
	           ->where(
	             $qb->expr()->eq('l.producto', $producto->getId())
	           )
	        ;

		return $sql->getQuery()->getSingleScalarResult();
	}
}
