<?php

namespace AppBundle\Repository;

/**
 * LoteFaltanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteFaltanteRepository extends \Doctrine\ORM\EntityRepository
{
}
