<?php

namespace AppBundle\Repository;

/**
 * LoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteRepository extends \Doctrine\ORM\EntityRepository
{
}
