<?php

namespace AppBundle\Repository;

/**
 * LoteAsignadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteAsignadoRepository extends \Doctrine\ORM\EntityRepository
{
}
