<?php

namespace AppBundle\Repository;

/**
 * LoteReservadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoteReservadoRepository extends \Doctrine\ORM\EntityRepository
{
}
