<?php

namespace AppBundle\Repository;

/**
 * RemitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemitoRepository extends \Doctrine\ORM\EntityRepository
{
}
