<?php

namespace AppBundle\Repository;

/**
 * TipoFabricacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoFabricacionRepository extends \Doctrine\ORM\EntityRepository
{
}
