version: '2'
services:
  admin-panel:
    build: .
    depends_on:
      - db
    ports:
      - "9060:9060"
    volumes:
      - ./docker/parameters.yml:/server/app/config/parameters.yml:rw
#      - ./:/server:rw
    container_name: container_app
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql-data-equals:/var/lib/mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_DATABASE: symfony-admin-starter-kit
      MYSQL_ROOT_PASSWORD: symfony-admin-starter-kit
      MYSQL_USER: symfony-admin-starter-kit
      MYSQL_PASSWORD: symfony-admin-starter-kit
  nginx:
    build: ./docker/nginx
    depends_on:
      - admin-panel
    ports:
      - 8000:80
    restart: always
    volumes_from:
      - admin-panel
    container_name: container_nginx