version: '2'
services:
  admin-panel:
    build: .
    depends_on:
      - db
    ports:
      - "9060:9060"
    volumes:
      - ./docker/parameters.yml:/server/app/config/parameters.yml:rw
      - ./:/server:rw
  db:
    image: mysql:5.7
    volumes:
      - /var/lib/mysql-data-prueba:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    build: ./docker/nginx
    depends_on:
      - admin-panel
    ports:
      - 8000:80
    restart: always
    volumes_from:
      - admin-panel
